CREATE TABLE MASTER(
  MASTER_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL
);

CREATE TABLE STUDENT(
  STUDENT_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL ,
  MASTER_ID BIGINT,
  FOREIGN KEY (MASTER_ID) REFERENCES MASTER(MASTER_ID)
)